feat: 사용자 로그인 화면 UI 구현 (#9, #10)
mash-up-kr/luvket pull request #61
Opened 2019-12-17 14:33 UTC by rohi404

### Short description
#9 #10 의 하위 과제인 사용자 로그인 화면 UI 구현

### Proposed changes
- Login 컴포넌트 생성
- 라우트(/login) 연결
- 로그인 페이지에 LoginButton 컴포넌트 추가
- 로그인 페이지에 로고 영역 추가
- 이미지 asset 추가(카카오톡, 페이스북, 로고)

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionally)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test
- [ ] Documentation
- [ ] Refactoring

### How to test (Optional)
- 제플린과 구현된 UI 비교

### Reference (Optional)
- Fixes(#9 #10)

2019-12-18 03:46 UTC, jus0k requested changes

2019-12-18 03:46 UTC, jus0k commented on package.json
> +    "dotenv": "^8.2.0",
`dotenv` 패키지는 어떤 걸 위해 설치한건가요?

2019-12-18 03:46 UTC, jus0k commented on src/views/App.tsx
> +          <Route exact path={RouteEnum.Login} component={Login} />
별것은 아니지만 라우트의 순서가 홈 -> 로그인 -> 초대 -> 응답 순이 더 좋아보이지 않을까 생각합니다!

2019-12-18 03:46 UTC, jus0k commented on src/views/Login/Login.tsx
> +const KakaoLoginClick = (): void => {};
- `FacebookLoginClick`과 `KakaoLoginClick`은 `Login` 컴포넌트에서 동작하는 함수기 때문에 컴포넌트 내부로 위치를 옮겨야 할 것 같아요!
- 이벤트 핸들러의 네이밍 규칙은 저희끼리 정하면 되는 것이지만 찬연이형이 [우선 여기](https://jaketrent.com/post/naming-event-handlers-react/) 링크를 참고하면 좋겠다고 해서 참고해서 변경하면 좋을 것 같아요~

2019-12-18 03:46 UTC, jus0k commented on src/views/Login/Login.tsx
> +    padding-bottom: 225px;
지금은 세로 640px 기준으로 디자인이 되어 있지만, 세로 길이가 길어질 경우 위치를 어떻게 잡으면 좋을지 (상단 기준인지, 버튼 영역을 제외한 영역의 중간인지) 를 디자이너와 상의한 후에 적용하면 좋을 것 같아요! 지금은 세로 화면이 길어질 경우 `padding bottom` 속성은 적용되지 않을 것 같다는 생각이 듭니다~

2019-12-18 03:46 UTC, jus0k commented on src/views/Login/Login.tsx
> +    padding-right: 10px;
`padding-left`와 `padding-right`는 `padding: 0 10px;`로 축약해서 쓰는게 더 좋지 않을까요~? 좌우를 기준으로 하니 나중에 변경할 때도 하나의 수치만 바꾸면 되기 때문에 축약형([MDN 문서](https://developer.mozilla.org/ko/docs/Web/CSS/padding))이 처음에는 익숙해지기 어렵겠지만 나중에 관리하기는 더 쉬울 것 같다는 생각이 듭니다!

2019-12-18 03:46 UTC, jus0k commented on src/views/Login/components/LoginButton.tsx
> +  // eslint-disable-next-line
여기 린트 꺼놓은 코드는 아마 전에 제가 작성했던 코드인 것 같은데 지금은 해당 린트 옵션을 꺼놨기 때문에 삭제해도 무방할 것 같아요~

2019-12-18 03:48 UTC, jus0k commented
d288fed68f50458a57dd481c80cdfb6a2c0a5232 의 커밋메세지에도 PR에 있던
- 로그인 페이지에 LoginButton 컴포넌트 추가
- 로그인 페이지에 로고 영역 추가
- 이미지 asset 추가(카카오톡, 페이스북, 로고)
이 내용들을 넣어주면 더 좋을 것 같다는 생각이 듭니다!

2019-12-20 00:13 UTC, chayeoi commented
패키지 매니저로 yarn을 사용하고 있기 때문에 `package-lock.json`은 지워주시면 깔끔할 거 같습니다~

2019-12-20 00:14 UTC, chayeoi commented on package.json
> +    "dotenv": "^8.2.0",
`dotenv`는 환경변수 사용할 때 필요한 패키지인데, CRA로 빌드된 앱에 내장되어 있어서 따로 설치하지 않아도 될 것 같습니다만, 혹시 설치하지 않았을 경우 정상동작하지 않았나요~?

2019-12-20 00:32 UTC, chayeoi commented
#9 와 #10 가 완료되려면 로그인 기능이 완전히 구현되어 사용자가 로그인할 수 있어야 하는데, 현재 PR에는 UI와 관련된 작업만 포함되어있습니다. #9 와 #10 에 대한 하위 태스크를 만드신 후 PR description에 해당 이슈를 연결해주시면 감사하겠습니다~

2019-12-20 00:32 UTC, chayeoi requested changes

2019-12-20 00:32 UTC, chayeoi commented on src/views/Login/Login.tsx
> +const KakaoLoginClick = (): void => {};
함수 이름에는 lowerCamelCase를 적용해주는게 좋겠습니다~ 😄

2019-12-20 00:32 UTC, chayeoi commented on src/views/Login/Login.tsx
> +      <img src={logo} alt="logo" />
이 부분은 앱의 제목 역할을 하는 부분이기 때문에 `h1`으로 마크업하고 [IR(Image Replacement) 기법](https://nuli.navercorp.com/sharing/blog/post/1132804)을 적용하는 것이 좋겠습니다~ 단어 그대로 "텍스트를 이미지로 대체한다"는 뜻인데요. 지금과 같이 앱의 가장 중요한 제목에 달랑 이미지만 박아놓았을 경우, 다음과 같은 문제가 있습니다.

1. 검색엔진 로봇이 이미지에 들어있는 텍스트를 추출해 인덱싱할 수 없기 때문에 SEO 관점에서 좋지 않습니다.
2. 스크린 리더기와 같은 음성 보조 도구를 통해 서비스를 이용하는 사용자들이 정보를 쉽게 파악할 수 없습니다.

IR 기법 관련해서 찾아보시고 잘 모르겠으면 얘기해주세요!~

2019-12-20 00:32 UTC, chayeoi commented on src/views/Login/Login.tsx
> +      <span css={s.description}>너와 나만의 약속</span>
이 부분은 `p` 태그로 마크업하고 `aria-describedby` 속성을 통해 제목에 대한 부연 설명임을 명시해주면 더 좋을 것 같습니다~

```html
<h1 aria-describedby="subtitle">럽킷</h1>
<p id="subtitle">너와 나만의 약속</p>
```

2020-01-08 17:26 UTC, chayeoi commented
하위 태스크 만드신 후 #9, #10 대신 해당 이슈를 링크로 연결해주시면 좋을 것 같습니다!

2020-01-19 06:53 UTC, rohi404 commented on src/views/Login/components/LoginButton.tsx
> +  // eslint-disable-next-line
넵~

2020-01-19 06:54 UTC, rohi404 commented on src/views/Login/Login.tsx
> +    padding-right: 10px;
넵~

2020-01-19 06:54 UTC, rohi404 commented on src/views/Login/Login.tsx
> +    padding-bottom: 225px;
넵~

2020-01-19 06:54 UTC, rohi404 commented on src/views/Login/Login.tsx
> +const KakaoLoginClick = (): void => {};
넵~

2020-01-19 06:54 UTC, rohi404 commented on src/views/App.tsx
> +          <Route exact path={RouteEnum.Login} component={Login} />
넵~

2020-01-19 06:54 UTC, rohi404 commented on package.json
> +    "dotenv": "^8.2.0",
넵 삭제할게여

2020-01-19 06:54 UTC, rohi404 commented on src/views/Login/Login.tsx
> +      <img src={logo} alt="logo" />
넵~

2020-01-19 06:55 UTC, rohi404 commented
하위태스크랑 연결한 PR 새로 등록하고 이거는 closed 하면 될까여?

2020-01-19 06:58 UTC, rohi404 commented on src/views/Login/Login.tsx
> +      <span css={s.description}>너와 나만의 약속</span>
p태그에 h1태그 둘다 aria-describedby 속성 넣어야 하나요?

2020-01-19 07:21 UTC, chayeoi commented on src/views/Login/Login.tsx
> +      <span css={s.description}>너와 나만의 약속</span>
아녀 `p` 태그에 `id` 지정해주고나서 `h1`에는 `aria-describedby`로 그 아이디 값을 연결시켜주믄 댐니다

2020-01-19 07:24 UTC, chayeoi commented
> 하위태스크랑 연결한 PR 새로 등록하고 이거는 closed 하면 될까여?

close는 하위 태스크 작업이 모두 완료되었을 때 같이 닫으면 됩니다 ㅎㅎ

예를 들어 "로그인 기능 구현" 작업의 하위 태스크를

1. UI 구현
2. API 연동

으로 나누었을 때, 두 하위 작업이 모두 완료되는 시점에 그 상위 태스크도 같이 닫아주면 될 것 같아요

2020-01-19 11:37 UTC, chayeoi requested changes

2020-01-19 11:37 UTC, chayeoi commented on src/views/Login/components/LoginButton.tsx
> +const LoginButton: React.FC<LoginButtonProps> = ({ label, icon, ...otherProps }) => (
버튼 텍스트는 `label` prop으로 받는 것보다 `children` prop으로 받는 게 더 자연스러울 것 같습니다~!

2020-01-21 15:54 UTC, chayeoi commented
master랑 sync 맞춰주세요!

2020-01-23 12:22 UTC, rohi404 commented on src/views/Login/components/LoginButton.tsx
> +const LoginButton: React.FC<LoginButtonProps> = ({ label, icon, ...otherProps }) => (
버튼 텍스트는 왜 `children` prop으로 받는게 더 자연스러운지 궁금합니다!

2020-01-24 04:05 UTC, chayeoi commented on src/views/Login/components/LoginButton.tsx
> +const LoginButton: React.FC<LoginButtonProps> = ({ label, icon, ...otherProps }) => (
DOM 엘리먼트에서 텍스트 콘텐츠는 보통 `<button label="클릭" />` 형태가 아니라 `<button>클릭</button>`과 같이 사용하기 때문에 그렇게 생각했습니다~

2020-01-26 04:59 UTC, chayeoi approved these changes

2020-01-27 06:41 UTC, yurim22 approved these changes

2020-02-12 12:03 UTC, YuChocopie approved these changes

2020-02-13 06:07 UTC, jus0k approved these changes

2020-02-13 08:11 UTC, merged